tel: +16135551234 55
tel_display: 613 555 1234 55
seo:
  tagline: Live the dream in an old-style English Cottage now!
location:
  country: England
  locality: Leamington Spa
  region: Warwickshire
  street_address: 1234 Roundabout Way
